-- Gameplay

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100					-- Days of client lag for decrease of gamespeed
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 100						-- Days of client lag for pause of gamespeed.
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36
NDefines.NGame.NAVAL_COMBAT_CONVOY_SIZE = 0.20				-- Size of a convoy in a naval battle. Used to determine the size of the fleet when intercepting convoy.

-- Diplo Stuff

NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_FROM_PRODUCTION = 20.0	-- Base value scaled by production capacity of country compared to biggest country
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.025				-- Each army unit owned by the source country contributes this amount of volunteers to the limit.
NDefines.NDiplomacy.TENSION_CB_WAR = 3								-- Amount of tension generated by a war with a CB
NDefines.NDiplomacy.TENSION_PUPPET = 1.5								-- Amount of tension generated by puppeting (per state)
NDefines.NDiplomacy.TENSION_GENERATE_WARGOAL = 0.5					-- Amount of tension generated by generating a wargoal against a country
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.05			-- Amount of tension generated for each sent division
NDefines.NDiplomacy.TENSION_CAPITULATE = 0.60						-- Scale of the amount of tension created by a countries capitulation.
NDefines.NDiplomacy.MAX_FEAR_VALUE = 100							-- Max fear value cap.
NDefines.NDiplomacy.MIN_FEAR_VALUE = -100							-- Min fear  value cap.
NDefines.NDiplomacy.BASE_FEAR_FACTOR = 0							-- Base fear factor in % for opinion
NDefines.NDiplomacy.BASE_TRUST_FACTOR = 100						-- Base trust factor in % for opinion.
NDefines.NDiplomacy.BASE_PEACE_ANNEX_FACTOR = 100				-- Base factor for annexation in %.
NDefines.NDiplomacy.BASE_SEND_ATTACHE_MAINTAIN_COST = 0			-- Political power cost each update when sending the attache to another country
NDefines.NDiplomacy.BASE_GENERATE_WARGOAL_DAILY_PP = 0.8	-- Daily pp cost for generation of wargoals # was 0.2
NDefines.NDiplomacy.WARGOAL_VERSUS_MAJOR_AT_WAR_REDUCTION = -0.4 	-- reduction of pp cost for wargoal vs major at war. # was -0.75
NDefines.NDiplomacy.WARGOAL_WORLD_TENSION_REDUCTION = -0.7			-- Reduction of pp cost for wargoal at 100% world tension, scales linearly # was -0.5
NDefines.NDiplomacy.TRADE_NEUTRAL_OPINION_FACTOR = 0.75			-- If Both fear and trust are 0, this is the neutral factor for trade
NDefines.NDiplomacy.TRADE_OPINION_FACTOR_FACTOR = 1.0				-- How much the factor should effect the possible trade amount. Setting TRADE_NEUTRAL_OPINION_FACTOR to 1.0 and TRADE_OPINION_FACTOR_FACTOR to 0 means opinion does nothing in regards to trade.
NDefines.NDiplomacy.TENSION_GENERATE_WARGOAL = 1					-- Amount of tension generated by generating a wargoal against a country
NDefines.NDiplomacy.MP_NUM_WINNERS_FOR_PEACE_PAUSE = 1				-- Number of human players as winners needed for peace conference to pause and open for everyone in multiplayer, needs to fullfill MP_NUM_LOSERS_FOR_PEACE_PAUSE as well.
NDefines.NDiplomacy.MP_NUM_LOSERS_FOR_PEACE_PAUSE = 1				-- Number of human players as losers needed for peace conference to pause and open for everyone in multiplayer, needs to fullfill MP_NUM_WINNERS_FOR_PEACE_PAUSE as well.
NDefines.NDiplomacy.MAX_PARTICIPANTS_FOR_MAJOR_COUNTRIES = 5		-- If we have more then x aggressors/defenders we only list major countries in tooltip for warscore progressbar or entry in world tension view
NDefines.NDiplomacy.VICTORY_POINT_WORTH_FACTOR = 25				-- multiplier when calcualting proince worth (surrender)	


-- Country Stuff




NDefines.NCountry.RESISTANCE_STRENGTH_FROM_VP = 0.0017			-- How much strength ticking speed gives each VP score.
NDefines.NCountry.RESISTANCE_STRENGTH_FROM_NEIGHBORS = 0.4 		-- Multiplies how much resistance can spread from one state to its neighbors, a state will spread whatever is highest of its victorypoints resistance increase or half of any of its neighbors spread, multiplied by this
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.009 	-- Modifier for army equipment reinforcement speed
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 20 		-- Modifier for army manpower reinforcement delivery speed (travel time)

NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = 0 					-- Default stability war factor # was -0.3	
NDefines.NCountry.MAJOR_MIN_FACTORIES = 60						-- need at least these many factories to become a major
NDefines.NCountry.INVASION_REPORT_EXPERATION_DAYS = 10			-- Invasion experation days

NDefines.NCountry.REINFORCEMENT_DELIVERY_SPEED_MIN = 0.35 			-- The distance from the supply region to capital should affect the speed only a little bit. Main factor for penalty is overcrowded areas, and not the route length.
NDefines.NCountry.EVENT_PROCESS_OFFSET = 25						-- Events are checked every X day per character or province (1 is ideal, but CPU heavy)

NDefines.NCountry.RESOURCE_LENDLEASE_PRIORITY = 0.2				-- Default convoy priority for export lend lease
NDefines.NCountry.STATE_CONTROLLER_VP_RATIO_FLIP = 0.5		-- If current state controller has less share than this of state total and no armies in it the state changes controller
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.2	-- Default stability rulling party popularity factor
NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = -0.1				-- Impact of being in offensive war
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.2				-- Impact of being in defensive war
NDefines.NCountry.FRONT_PROVINCE_SCORE_HOSTILE_TROOPS = -1 		-- If province score in a front is below this value we are losing territory, and hostile troop alert will show.
NDefines.NCountry.THEATRES_BIND_BORDER_DISTANCE = 25000			-- Map distance (before sqrt) between the center of the borders that determines if theatres should be bound or not.
NDefines.NCountry.MIN_NAVAL_SUPPLY_EFFICIENCY = 0.15				-- Min ratio when supplies will be considered delivered from the capital by naval path
NDefines.NCountry.STATE_VALUE_RESEOURCE_MULT = 0.05				-- The Value of each resource in a state ( Value is used to determine costs in peace conference and PP cost to occupy)
NDefines.NCountry.BASE_SURRENDER_LIMIT = 0.75						-- Base level of occupation required for country surrender
NDefines.NCountry.INTERCEPTION_WAR_SUPPORT_SCALE = 0.00002		-- Scaling of interceptions to war support impact
NDefines.NCountry.INTERCEPTION_BOMBING_WAR_SUPPORT_IMPACT = 0.3	-- Max impact of interceptions on the war support
NDefines.NCountry.ATTACHE_XP_SHARE = 0.01							-- was 0.2 Country received xp from attaches
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.03					-- Max ammount of special forces battalions is total number of non-special forces battalions multiplied by this and modified by a country modifier
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 18					-- You can have a minimum of this many special forces battalions, regardless of the number of non-special forces battalions you have, this can also be modified by a country modifier
NDefines.NCountry.BASE_FUEL_LAND_LEASE_SPEED = 50				-- base value for maximum fuel that can be land leased per hour
NDefines.NCountry.FUEL_LAND_LEASE_RATIO = 1.0					-- multiplier for guel gain that is added to maximum fuel that can be land leased per hour
NDefines.NCountry.FUEL_LEASE_CONVOY_RATIO = 0.0015				-- was 0.0005 -- num convoys needed per fuel land lease 



-- Production Stuff

NDefines.NProduction.MAX_EQUIPMENT_RESOURCES_NEED = 4 	-- Max number of different strategic resources an equipment can be dependent on.
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 20		-- was 15 -- Max number of factories that can be assigned a single production line.
NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 40
NDefines.NProduction.BASE_FACTORY_SPEED = 2.5 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 2.5 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).

NDefines.NProduction.BASE_FACTORY_EFFICIENCY_GAIN = 0.9		-- Base efficiency factor.
NDefines.NProduction.EQUIPMENT_LEND_LEASE_WEIGHT_FACTOR = 0.001 -- was 0.01 -- Base equipment lend lease factor
NDefines.NProduction.MAX_LINE_RESOURCE_PENALTY = 90		-- Max penalty factor for production lines lacking strategic resources in %.
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_PARENT_CHANGE_FACTOR = 50		-- Base factor for changing production parent<->children in %.
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 50000			-- was 100000 -- How many deployment lines minimum can be training
NDefines.NProduction.MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.50	-- was 0.75 -- Ratio which % of army in field can be trained

NDefines.NProduction.LICENSE_IC_COST_YEAR_INCREASE = 0					-- IC cost equipment for every year of equipment after 1936
NDefines.NProduction.LICENSE_EQUIPMENT_BASE_SPEED = -0.4				-- base MIC speed modifier for licensed equipment
NDefines.NProduction.BASE_LICENSE_IC_COST = 0							-- Base IC cost for lended license


-- Oil Suff 

NDefines.NCountry.STARTING_FUEL_RATIO = 0.5						-- starting fuel ratio compared to max fuel for countries
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 1.5						-- base amount of fuel gained hourly per excess oil
NDefines.NCountry.BASE_FUEL_GAIN = 2.0							-- base amount of fuel gained hourly, independent of excess oil
NDefines.NCountry.BASE_FUEL_CAPACITY = 50000						-- base amount of fuel capacity

-- trade stuff 

NDefines.NTrade.BASE_TRADE_FACTOR = 100					-- This is the base trade factor
NDefines.NTrade.ANTI_MONOPOLY_TRADE_FACTOR_THRESHOLD = 0.8	-- What percentage of resources has to be sold to the buyer for the anti-monopoly factor to take effect
NDefines.NTrade.ANTI_MONOPOLY_TRADE_FACTOR = -25			-- This is added to the factor value when anti-monopoly threshold is exceeded

NDefines.NTrade.BASE_LAND_TRADE_RANGE = 750

-- Building Stuff

NDefines.NBuildings.MAX_BUILDING_LEVELS = 40			-- Max levels a building can have.
NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 100		-- Each level of airbase building multiplied by this, gives capacity (max operational value). Value is int. 1 for each airplane.
NDefines.NBuildings.BASE_FACTORY_REPAIR = 0.4			-- Default repair rate before factories are taken into account
NDefines.NBuildings.BASE_FACTORY_REPAIR_FACTOR = 6.0	-- Factory speed modifier when repairing.
NDefines.NBuildings.MAX_SHARED_SLOTS = 50				-- Max slots shared by factories
NDefines.NBuildings.NAVALBASE_CAPACITY_MULT = 15.0		-- Each level of navalbase building multiplied by this, gives max capacity. Value is float. Each ship takes port_capacity_usage space.
NDefines.NBuildings.NAVALBASE_REPAIR_MULT = 1.000		-- Each level of navalbase building repairs X strength. The value is spread on all ships needed reparation. Fe Navalbase lvl 5 x 0.5 str repair = 2.5 str repaired over 10 ships, so each ship repair hourly 0.25 str.
NDefines.NBuildings.RADAR_RANGE_BASE = 15				-- Radar range base, first level radar will be this + min, best radar will be this + max
NDefines.NBuildings.RADAR_RANGE_MIN = 15				-- Radar range (from state center to province center) in measure of map pixels. Exluding techs.
NDefines.NBuildings.RADAR_RANGE_MAX = 120				-- Range is interpolated between building levels 1-15.
NDefines.NBuildings.RADAR_INTEL_EFFECT = 30			-- Province covered by radar increases intel by 10 (where 255 is max). Province may be covered by multiple radars, then the value sums up.
NDefines.SABOTAGE_FACTORY_DAMAGE = 75.0		-- How much damage takes a factory building in sabotage when state is occupied. Damage is mult by (1 + resistance strength), i.e. up to 2 x base value.	



	

-- Research Stuff 

NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 6 -- Base year ahead penalty
NDefines.NTechnology.BASE_TECH_COST = 85				-- Base cost for a tech. multiplied with tech cost and ahead of time penalties
NDefines.NTechnology.DEFAULT_XP_RESEARCH_COST = 100			-- default xp cost of a research to speed up the process
NDefines.NTechnology.DEFAULT_XP_RESEARCH_BONUS = 1.5		-- default research bonus gained when xp is used to research an item
NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 50.0		-- Base amount of research points a country can save per slot.
NDefines.NTechnology.LICENSE_PRODUCTION_TECH_BONUS = 0.15	-- License production tech bonus
NDefines.NTechnology.MIN_RESEARCH_SPEED = 0.1				-- research speed can't go below this value


-- Political stuff

NDefines.NPolitics.DEFAULT_OCCUPATION_POLICY = 3		-- Defaullt value for occupation policy
NDefines.NPolitics.INSTANT_WIN_POPULARITY_WIN = 55 -- New party popularity
NDefines.NPolitics.ARMY_LEADER_COST = 2						-- was 5 -- cost for recruiting new leaders, 'this value' * number_of_existing_leaders_of_type


-- Military Stuff

NDefines.NMilitary.HOURLY_ORG_MOVEMENT_IMPACT = -0.2		-- how much org is lost every hour while moving an army.
NDefines.NMilitary.ZERO_ORG_MOVEMENT_MODIFIER = -0.9		-- speed impact at 0 org.
NDefines.NMilitary.INFRA_ORG_IMPACT = 0.75				-- scale factor of infra on org regain.
NDefines.NMilitary.INFRASTRUCTURE_MOVEMENT_SPEED_IMPACT = -0.02	-- speed penalty per infrastucture below maximum.
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 10				-- how many armies a field marshall is limited to. 0 = inf, < 0 = blocked 
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 240			-- how many divisions a field marshall is limited to. 0 = inf, < 0 = blocked 
NDefines.NMilitary.MAX_DIVISION_BRIGADE_WIDTH = 5			-- Max width of regiments in division designer.
NDefines.NMilitary.MAX_DIVISION_BRIGADE_HEIGHT = 6			-- Max height of regiments in division designer.
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2			-- Max width of support in division designer.
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 1 	--Base cost to unlock a regiment slot,
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1	--Base cost to change a regiment column.
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 5 	--Base cost to unlock a support slot



NDefines.NMilitary.LAND_COMBAT_FORT_DAMAGE_CHANCE = 05		-- chance to get a hit to damage on forts. (out of 100)

-- air impact on land combats

NDefines.NMilitary.LAND_AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.08    -- air global damage modifier
NDefines.NMilitary.LAND_AIR_COMBAT_ORG_DAMAGE_MODIFIER = 0.08    -- global damage modifier
NDefines.NMilitary.LAND_AIR_COMBAT_MAX_PLANES_PER_ENEMY_WIDTH = 5 -- how many CAS/TAC can enter a combat depending on enemy width there

-- Land combat general regulation

NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.075        -- global damage modifier... but some equipment is returned at end of battles see : EQUIPMENT_COMBAT_LOSS_FACTOR
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.025        -- global damage modifier
NDefines.NMilitary.BASE_CHANCE_TO_AVOID_HIT = 75                 -- Base chance to avoid hit if defences left.
NDefines.NMilitary.CHANCE_TO_AVOID_HIT_AT_NO_DEF = 30	           -- chance to avoid hit if no defences left.

-- Effects on experience and equipment

NDefines.NMilitary.EXPERIENCE_LOSS_FACTOR = 0.85                 -- percentage of experienced solders who die when manpower is removed
NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 0.55	 	       -- % of equipment lost to strength ratio in combat, so some % is returned if below 1

-- Armor case

NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE = 4   -- extra damage dice if our armor outclasses enemy
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 6   -- extra damage dice if our armor outclasses enemy
NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_DEFLECTION_FACTOR = 0.75 -- damage reduction if armor outclassing enemy
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_DEFLECTION_FACTOR = 0.75 -- damage reduction if armor outclassing enemy

-- Paradrops 
NDefines.NMilitary.PARACHUTE_COMPLETE_ORG = 0.4				   -- Organisation value (in %) after unit being dropped, regardless if failed, disrupted, or successful.
NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_DURATION = 12   -- penalty in org regain after being parachuted. Value is in hours.
NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_MULT = -0.5	   -- penalty to org regain after being parachuted.


NDefines.NMilitary.BASE_COMBAT_WIDTH = 80                       -- base combat width
NDefines.NMilitary.ADDITIONAL_COMBAT_WIDTH = 40                  -- more opened up by support attack
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.4         -- effect on defense due to enemy air superiorty
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.5     -- was -0.5 - effect on speed due to enemy air superiority

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999 					--Max army experience a country can store
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999					--Max navy experience a country can store
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999					--Max air experience a country can store

NDefines.NMilitary.SLOWEST_SPEED = 1
NDefines.NMilitary.DIG_IN_FACTOR = 0.01 -- 0.02
NDefines.NMilitary.AIR_SUPPORT_BASE = 0.3                        -- CAS bonus factor for air support moddifier for land unit in combat
NDefines.NMilitary.REINFORCE_CHANCE = 0.04                 	   -- base chance to join combat from back line when empty

NDefines.NMilitary.LOW_ORG_FOR_ATTACK = 0.5                      -- at what org % we start affecting speed when doign hostile moves. scales down ZERO_ORG_MOVEMENT_MODIFIER
NDefines.NMilitary.PLANNING_DECAY = 0.02
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.02				-- Amount of planning lost due to player manual order
NDefines.NMilitary.PLAN_CONSIDERED_GOOD = 0.5					-- Plan evaluations above this value are considered more or less safe
NDefines.NMilitary.PLAN_CONSIDERED_BAD = 0.05					-- Plan evaluations below this value are considered unsafe
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 5		-- The battle plan system will only automatically attack provinces in pockets that has no resistance and are no bigger than these many provinces
NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 10.0				-- The higher the value, the less it should crowd provinces with multiple attacks.

NDefines.NMilitary.PLAN_AREA_DEFENSE_FORT_IMPORTANCE = 1.0		-- Used when calculating the calue of defense area provinces for the battle plan system, works as multipliers on the rest
NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -1.5					-- over combat width penalty per %.
NDefines.NMilitary.STRATEGIC_SPEED_BASE = 5.0                 	-- Speed of strategic redeployment
NDefines.NMilitary.STRATEGIC_INFRA_SPEED = 15.0                   -- Max of additional speed gained trouh=gh level for strategic redeployment per infra
NDefines.NMilitary.FASTER_ORG_REGAIN_LEVEL = 0.2
NDefines.NMilitary.FASTER_ORG_REGAIN_MULT = 0.7
NDefines.NMilitary.ACCLIMATIZATION_SPEED_GAIN = 0.08				-- A variable used to balance the overall speed of gaining the acclimatization
NDefines.NMilitary.ACCLIMATIZATION_LOSS_SPEED_FACTOR = 1.0		-- Loosing one acclimatization while being under affect of the opposite climate should cause it to drop down much faster than gaining.
NDefines.NMilitary.UNIT_LEADER_MODIFIER_COOLDOWN_ON_GROUP_CHANGE = 3		-- time in days for a unit leader to regain its modifiers

NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 5				-- Most xp you can gain per day
NDefines.NMilitary.ALERT_LOW_SUPPLY_LEVEL = 0.8


NDefines.NMilitary.TRAINING_ATTRITION = 0.04		  			   -- amount of extra attrition from being in training

NDefines.NMilitary.OVERSEAS_LOSE_EQUIPMENT_FACTOR = 1.0		   -- percentage of equipment lost disbanded overseas
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.0       -- percentage of manpower returned when an encircled unit is disbanded
NDefines.NMilitary.LAND_COMBAT_ATTACKER_WINNING = 0.65		  	-- Above this means attacker is winning
NDefines.NMilitary.LAND_COMBAT_DEFENDER_WINNING = 0.35		  	-- Below this means defender is winning
NDefines.NMilitary.PLAN_SUPPLY_FACTOR = 0.2						-- Factor applied to available supply on a front location when determining priority
NDefines.NMilitary.ARMOR_VS_AVERAGE = 0.65			                -- how to weight in highest armor & pen vs the division average
NDefines.NMilitary.PEN_VS_AVERAGE = 0.5
NDefines.NMilitary.DISBAND_MANPOWER_LOSS = 0.0
NDefines.NMilitary.MIN_DIVISION_DEPLOYMENT_TRAINING = 0.4			-- Min level of division training
NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 4					-- If a units path is at least this long to reach its front location, it will strategically redeploy.
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.05				-- after a successful land combat, ratio of the equipments that are being captured/salvaged from enemy's lost equipment


NDefines.NMilitary.LEND_LEASE_FIELD_EXPERIENCE_SCALE = 0.005		-- was 0.005 Experience scale for lend leased equipment used in combat.

-- meaningfull combat

NDefines.NMilitary.COMBAT_VALUE_ORG_IMPORTANCE = 1.3		-- Multiplier on TotalOrganisation when determining the combat value of a division
NDefines.NMilitary.RECON_SKILL_IMPACT = 7 -- how many skillpoints is a recon advantage worth when picking a tactic.
NDefines.NMilitary.SPOTTING_QUALITY_DROP_HOURS = 5 	-- Each X hours the intel quality drops after unit was spotted.
NDefines.NMilitary.COMBAT_MINIMUM_TIME = 7			-- Shortest time possible for a combat in hours
NDefines.NMilitary.LAND_COMBAT_COLLATERAL_FACTOR = 0.007		   -- Factor to scale collateral damage to infra and forts with.
NDefines.NMilitary.COMBAT_MOVEMENT_SPEED = 0.25	               -- speed reduction base modifier in combat
NDefines.NMilitary.TACTIC_SWAP_FREQUENCEY = 12                   -- hours between tactic swaps
NDefines.NMilitary.INITIATIVE_PICK_COUNTER_ADVANTAGE_FACTOR  = 0.45 -- advantage per leader level for picking a counter
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.8           -- large river crossing
NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY = -0.30           -- small river crossing
NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY_LARGE = -0.7     -- large river crossing
NDefines.NMilitary.BASE_FORT_PENALTY = -0.20 					   -- fort penalty		#HOI4TGW ::: BASE_FORT_PENALTY = -0.15
NDefines.NMilitary.MULTIPLE_COMBATS_PENALTY = -0.6               -- defender penalty if attacked from multiple directions
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE_STEEPNESS = 120 -- how quickly defense approaches the max impact diminishing returns curve
NDefines.NMilitary.ENCIRCLED_PENALTY = -0.45                      -- penalty when completely encircled
NDefines.NMilitary.UNIT_DIGIN_CAP = 7                           -- how "deep" you can dig you can dig in until hitting max bonus
NDefines.NMilitary.UNIT_DIGIN_SPEED = 0.9						   -- how "deep" you can dig a day.
NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.3              -- percentage of (max) org loss on takign enemy province
NDefines.NMilitary.PLAN_SUPPLY_FACTOR = 0.2						-- Factor applied to available supply on a front location when determining priority


-- leaders xp
NDefines.NMilitary.FIELD_MARSHAL_XP_RATIO = 0.5					-- xp gain ratio for army group leaders
NDefines.NMilitary.MAX_RELATIVE_COMBAT_DAMAGE_TO_MODIFY_XP =  4			-- you gain more XP if you are doing more damage relative to enemy, this is the max relative amount to gain following RATe
NDefines.NMilitary.XP_GAIN_FACTOR_FOR_MAX_RELATIVE_COMBAT_DAMAGE =  4	-- XP factor scaling for max relative combat damage
NDefines.NMilitary.XP_DECAY_RATE_PER_HOUR_IN_COMBAT = 0.03				-- you get reduced XP as combat drags
NDefines.NMilitary.MIN_XP_RATE_TO_DECAY = 0.01						-- minimum XP factor for dragged combats
NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 35 						-- fixed XP gain per overrun unit
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 35                          -- extra multiplier on XP gain on shattering an encircled enemy
NDefines.NMilitary.UNIT_LEADER_MAX_SKILL_XP_BOOST_FACTOR = 2.0   -- When a commander is at maximum level, he gains ranks faster.
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.1  -- XP gain per unit in combat
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.45 				   -- Base xp gain for traits per hour for armies.
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR =  0.25
NDefines.NMilitary.LEADER_EXPERIENCE_SCALE = 0.25
NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.0002

-- Leaders skills 

NDefines.NMilitary.COMMANDER_LEVEL_UP_STAT_COUNT = 3 		--was 3		-- num stats gained on level up
NDefines.NMilitary.COMMANDER_LEVEL_UP_STAT_WEIGHTS = {8, 4, 1, 2} -- was {5, 5, 5, 5} -- level up stat random base weights attack, defense, planning, logistics

NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 75.0 --30.0                    -- cost of promoting a leader


-- Supply 


NDefines.NCountry.VP_TO_SUPPLY_BASE = 1.5							-- Bonus to supply from a VP, no matter the level
NDefines.NCountry.VP_TO_SUPPLY_BONUS_CONVERSION = 0.5 -- 0.4		 -- Bonus to supply local supplies from Victory Points, multiplied by this aspect and rounded to closest integer
NDefines.NCountry.SUPPLY_FROM_DAMAGED_INFRA = 0.4                -- damaged infrastructure counts as this in supply calcs
NDefines.NCountry.SUPPLY_BASE_MULT = 0.25							-- multiplier on supply base values
NDefines.NCountry.SUPPLY_BONUS_FROM_INPUT = 0.30					-- % of supply bonus from input area.
NDefines.NCountry.SUPPLY_PATH_MAX_DISTANCE = 10						-- When supply route reach more than X nodes, the manpower+equipment delivery speed reach 100% penalty.
NDefines.NCountry.SUPPLY_CONVOY_FACTOR = 1					-- How many convoys each supply needs
NDefines.NBuildings.SUPPLY_PORT_LEVEL_THROUGHPUT = 3   -- supply throughput per level of naval base
NDefines.NBuildings.INFRA_TO_SUPPLY = 2					-- was 2
NDefines.NBuildings.INFRA_TO_SUPPLY_COEFF = 1.25
NDefines.NMilitary.ATTRITION_DAMAGE_ORG = 0.3
NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.005
NDefines.NMilitary.SUPPLY_USE_FACTOR_MOVING = 1.5                -- supply use when moving/fighting vs inactive
NDefines.NMilitary.SUPPLY_USE_FACTOR_INACTIVE = 0.95
NDefines.NMilitary.SUPPLY_GRACE = 72		-- troops always carry 3 days of food and supply
NDefines.NMilitary.MAX_OUT_OF_SUPPLY_DAYS = 30 				   -- how many days of shitty supply until max penalty achieved
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.1                 -- max attrition when out of supply
NDefines.NMilitary.OUT_OF_SUPPLY_SPEED = -0.9                    -- max speed reduction from supply
NDefines.NMilitary.NON_CORE_SUPPLY_SPEED = -0.7				   -- we are not running on our own VP supply so need to steal stuff along the way
NDefines.NMilitary.OUT_OF_SUPPLY_MORALE = -0.3                   -- max org regain reduction from supply




-- LAND/ARMY FUEL
NDefines.NMilitary.ARMY_FUEL_COST_MULT = 0.7						-- was 0.5 -- fuel cost multiplier for all army related stuff
NDefines.NMilitary.FUEL_PENALTY_START_RATIO = 0.33								-- was 0.25 -- ratio of fuel in an army to start getting penalties
--NDefines.NMilitary.SURPLUS_SUPPLY_RATIO_FOR_ZERO_FUEL_FLOW = 1.5		-- was 0.5 -- if a supply chunk has more supply needed than this ratio + 1 compared to its max supply flow, the units inside the chiunk will get no fuel 
--NDefines.NMilitary.ARMY_MAX_FUEL_FLOW_MULT = 0.6					-- was 2.0 -- max fuel ratio that an army can get per hour, multiplied by supply situation
NDefines.NMilitary.ARMY_COMBAT_FUEL_MULT =   0.4				-- was 1.0	-- fuel consumption ratio in combat (plus ARMY_MOVEMENT_FUEL_MULT if you are also moving. ie offensive combat)
NDefines.NMilitary.ARMY_TRAINING_FUEL_MULT = 0.67				-- was 1.0	-- fuel consumption ratio while training
NDefines.NMilitary.ARMY_IDLE_FUEL_MULT = 0.2					-- was 0.0	-- fuel consumption ratio while just existing
NDefines.NMilitary.ARMY_NAVAL_TRANSFER_FUEL_MULT = 0.2			-- was 0.0 -- fuel consumption ratio while naval transferring
NDefines.NMilitary.ARMY_STRATEGIC_DEPLOYMENT_FUEL_MULT = 0.2		-- was 0.0 -- fuel consumption ratio while doing strategic deployment
NDefines.NMilitary.OUT_OF_FUEL_EQUIPMENT_MULT = 0.25				-- was 0.1 -- ratio of the stats that you get from equipments that uses fuel and you lack it
NDefines.NMilitary.FUEL_CAPACITY_DEFAULT_HOURS = 216              -- was 96 -- default capacity if not specified



-- PLANE STUFF

NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 150					-- Max stats
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 150
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 150
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 1500
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 150

NDefines.NAir.COMBAT_MULTIPLANE_CAP = 2.0						-- was 3.0 - How many planes can shoot at each plane on other side ( if there are 100 planes we are atttacking COMBAT_MULTIPLANE_CAP * 100 of our planes can shoot )
NDefines.NAir.ACCIDENT_CHANCE_BASE = 0.10						-- was 0.05	- Base chance % (0 - 100) for accident to happen. Reduced with higher reliability stat.


NDefines.NAir.AIR_DEPLOYMENT_DAYS = 10							-- was 5 -- Days to deploy one air wing
NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.01				-- was 0.02	-- Global speed multiplier for airplanes (affects fe.transferring to another base)



NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.2				-- was 0.8	-- Anti Air Gun Damage factor
NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0.40						-- was 0.25	-- % of picking the wrong target

NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.010 				-- was 0.005	--Factor on country Air XP gained from wing training

NDefines.NAir.COMBAT_DAMAGE_SCALE = 0.25				-- was 0.1			-- Higher value = more shot down planes
NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 50 --5                    -- same as above but used inside naval combat for carrier battles


	



NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_TACTICAL_BOMBER = 0.1	-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_STRATEGIC_BOMBER = 0.036	-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_DEFAULT = 0.5				-- Default how much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_CAS = 0.75				-- How much efficiency to regain per day. Gain applied hourly.
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_NAVAL_BOMBER = 0.192		-- How much efficiency to regain per day. Gain applied hourly.
EFFICIENCY_REGION_CHANGE_DAILY_GAIN_FIGHTER = 0.75			-- How much efficiency to regain per day. Gain applied hourly.


NDefines.NAir.EFFICIENCY_REGION_CHANGE_PENALTY_FACTOR = 0.99			-- Penalty applied for changing region
	

NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 0.75 -- original 1.00 Balancing value to convert equipment stat anti_air_attack to the damage reduction modifier apply to incoming air attacks against units with AA.
NDefines.NAir.ANTI_AIR_MAXIMUM_DAMAGE_REDUCTION_FACTOR = 0.65

NDefines.NAir.NAVAL_KAMIKAZE_DAMAGE_MULT = 10.0  -- vanilla is like 20

NDefines.NAir.PORT_STRIKES_DELAY_MULTIPLIER = 0.5  --2					-- multplies HOURS_DELAY_AFTER_EACH_COMBAT if port strikes
NDefines.NAir.PORT_STRIKE_ENEMY_SUPERIORITY_LIMIT = 1.3 --1.1			-- Min air superiority for performing of naval strike

NDefines.NAir.HOURS_DELAY_AFTER_EACH_COMBAT = 7					-- How many hours needs the wing to be ready for the next combat. Use for tweaking if combats happens too often. (generally used as double because of roundtrip)
NDefines.NAir.CARRIER_HOURS_DELAY_AFTER_EACH_COMBAT = 8          -- how often carrier planes do battle inside naval combat
NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 4.0					-- Balancing value to convert damage ( naval_strike_attack * hits ) to Organisation reduction.
NDefines.NAir.AA_INDUSTRY_AIR_DAMAGE_FACTOR = -0.15				-- 5x levels = 60% defense from bombing



	
-- SHIP STUFF

NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 0.5									-- was 0.25
NDefines.NNavy.HEAVY_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.05 				-- heavy gun attack value is divided by this value * 100 and added to shore bombardment modifier 
NDefines.NNavy.LIGHT_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.01                 -- light gun attack value is divided by this value * 100 and added to shore bombardment modifier

NDefines.NNavy.TRAINING_DAILY_COUNTRY_EXP_FACTOR = 0.0005						-- was 0.001 -- Factor used to scale the Daily Country Navy XP gain



NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.05							-- Balancing value to convert averaged equipment stats (anti_air_targetting and naval_strike_agility) to probability chances of airplane being hit by navies AA.
NDefines.NNavy.ANTI_AIR_ATTACK_TO_AMOUNT = 0.005							-- Balancing value to convert equipment stat anti_air_attack to the random % value of airplanes being hit.
NDefines.NNavy.AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING	= 0.7           -- AA penalty at 0% positioning


NDefines.NNavy.NAVAL_TRANSFER_BASE_SPEED = 6                                -- was 6 -- base speed of units on water being transported

NDefines.NNavy.COMBAT_BASE_HIT_CHANCE = 0.05									-- base chance for hit
NDefines.NNavy.COMBAT_EVASION_TO_HIT_CHANCE = 0.025							-- we take ship evasion stats, and mult by this value, so it gives hit chance reduction. So if reduction is 0.025 and ship evasion = 10, then there will be 0.25 (25%) lower hit chance. (Fe. 50% base -25% from evasion +10% bcoz it's very close).
NDefines.NNavy.COMBAT_TORPEDO_CRITICAL_DAMAGE_MULT = 3.0						-- multiplier to damage when got critical hit from torpedo. (Critical hits are devastating as usualy torpedo_attack are pretty high base values).
NDefines.NNavy.COMBAT_CHASE_RESIGNATION_HOURS = 10								-- Before we resign chasing enemy, give them some minimum time so the combat doesn't end instantly.
NDefines.NNavy.COMBAT_SHIP_SPEED_TO_FIELD_FACTOR = 0.02						-- Modifier to the ships speed in the combat. For better balance, make it lower to slow down the speed of approaching.
NDefines.NNavy.COMBAT_MAX_GROUPS = 2										-- Max amount of "Fire Exchange" groups (FEX).
NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.6								-- required naval supremacy to perform invasions on an area


-- Navy stuff

NDefines.NNavy.UNIT_TRANSFER_SPOTTING_SPEED_MULT = 2.0 -- 5.0						-- spotting speed mult against unit transfers





NDefines.NNavy.CAPITALS_TO_CARRIER_RATIO = 0.25 --1.5					-- capital to carrier count in carrier taskfoces
NDefines.NNavy.SCREENS_TO_CAPITAL_RATIO = 3.0 -- 4.0				-- screens to capital/carrier count in carrier & capital taskforces
NDefines.NNavy.PRIDE_OF_THE_FLEET_UNASSIGN_COST = 50 --100							-- cost to unassign/replace pride of the fleet

NDefines.NNavy.NAVAL_MINES_IN_REGION_MAX = 250 -- 1000								-- Max number of mines that can be layed by the ships. The value should be hidden from the user, as we present % so it's an abstract value that should be used for balancing.
NDefines.NNavy.NAVAL_MINES_PLANTING_SPEED_MULT = 0.01 -- 0.0001						-- Value used to overall balance of the speed of planting naval mines
NDefines.NNavy.NAVAL_MINES_SWEEPING_SPEED_MULT = 0.009 -- 0.00009						-- Value used to overall balance of the speed of sweeping naval mines
NDefines.NNavy.NAVAL_MINES_DECAY_AT_PEACE_TIME = 0.25 -- 0.25							-- How fast mines are decaying in peace time. Planting mines in peace time may be exploitable, so it's blocked atm. That's why after war we should decay them too.
NDefines.NNavy.NAVAL_MINES_SWEEPERS_REDUCTION_ON_PENALTY_EFFECT = 3.3			-- How much is the task force's sweeping attribute reducing the penalty effect.
NDefines.NNavy.NAVAL_MINES_ENCRYPTION_VS_DECRYPTION_FACTOR = 0.3				-- Better our decryption over enemy encryption will reduce the penalties from the enemy mines in the region. This value is a factor to be used for balancing.
NDefines.NNavy.NAVAL_MINES_NAVAL_SUPREMACY_FACTOR = 1.0						-- Factor for max amount of mines increasing naval supremacy

NDefines.NNavy.NAVAL_INVASION_SPOTTING_SPEED_MULT = 3.0
NDefines.NNavy.SUBMARINE_REVEALED_TIMEOUT = 24
NDefines.NNavy.COMBAT_MIN_DURATION = 24
NDefines.NNavy.SUBMARINE_HIDE_TIMEOUT = 24						-- Amount of in-game-hours that takes the submarine (with position unrevealed), to hide.
NDefines.NNavy.AGGRESSION_LIGHT_GUN_EFFICIENCY_ON_LIGHT_SHIPS = 0.5 -- ratio for scoring for different gun types against light ships
NDefines.NNavy.AGGRESSION_HEAVY_GUN_EFFICIENCY_ON_LIGHT_SHIPS = 0.25 -- ratio for scoring for different gun types against light ships
NDefines.NNavy.AGGRESSION_TORPEDO_EFFICIENCY_ON_LIGHT_SHIPS = 0.8	-- ratio for scoring for different gun types against light ships
NDefines.NNavy.AGGRESSION_LIGHT_GUN_EFFICIENCY_ON_HEAVY_SHIPS = 0.1 -- ratio for scoring for different gun types against heavy ships
NDefines.NNavy.AGGRESSION_HEAVY_GUN_EFFICIENCY_ON_HEAVY_SHIPS = 0.5 -- ratio for scoring for different gun types against heavy ships
NDefines.NNavy.AGGRESSION_TORPEDO_EFFICIENCY_ON_HEAVY_SHIPS = 1.0   -- ratio for scoring for different gun types against heavy ships

NDefines.NNavy.BASE_GUN_COOLDOWNS = { -- number of hours for a gun to be ready after shooting
		1.0,	-- big guns
		4.0,	-- torpedos
		1.5	-- small guns	
}
NDefines.NNavy.MISSION_SUPREMACY_RATIOS = { -- supremacy multipliers for different mission types
		0.0, -- HOLD
		0.1, -- PATROL		
		0.1, -- STRIKE FORCE 
		0.5, -- CONVOY RAIDING
		0.5, -- CONVOY ESCORT
		0.3, -- MINES PLANTING	
		0.3, -- MINES SWEEPING	
		0.0, -- TRAIN
		0.0, -- RESERVE_FLEET`
		1.0, -- NAVAL_INVASION_SUPPORT
}
NDefines.NNavy.SHIP_TO_FLEET_ANTI_AIR_RATIO	= 0.15
NDefines.NNavy.MIN_HIT_PROFILE_MULT = 0.05

-- XP for ships and admirals

NDefines.NNavy.UNIT_EXPERIENCE_SCALE = 0.5   -- was 1.0
NDefines.NNavy.LEADER_EXPERIENCE_SCALE = 0.5  -- was 1.0




--Focus 		
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30

---------------------------------------------------------------------------------------------------------

-- AI 

-- Research 

NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 1
NDefines.NAI.RESEARCH_LAND_DOCTRINE_NEED_GAIN_FACTOR = 0.5                      	-- Multiplies value based on relative military industry size / country size.
NDefines.NAI.RESEARCH_NAVAL_DOCTRINE_NEED_GAIN_FACTOR = 0.5                       -- Multiplies value based on relative naval industry size / country size.
NDefines.NAI.RESEARCH_AIR_DOCTRINE_NEED_GAIN_FACTOR = 0.5                         -- Multiplies value based on relative number of air base / country size.
NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 2
NDefines.NAI.RESEARCH_NEW_WEIGHT_FACTOR = 0			                            -- Impact of previously unexplored tech weights. Higher means more random exploration.
NDefines.NAI.RESEARCH_BONUS_FACTOR = 3 				                       		-- To which extent AI should care about bonuses to research
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 2.5		                            -- To which extent AI should care about ahead of time penalties to research
NDefines.NAI.RESEARCH_BASE_DAYS = 0					                            -- AI adds a base number of days when weighting completion time for techs to ensure it doesn't only research quick techs
NDefines.NAI.RESEARCH_MULTI_DOCTRINE_SCORE = 0
NDefines.NAI.XP_RATIO_REQUIRED_TO_RESEARCH_WITH_XP = 3.0		-- AI will at least need this amount of xp compared to cost of a tech to reserch it with XP			
NDefines.NAI.RESEARCH_WITH_XP_AI_WEIGHT_MULT = 1.5 				-- AI will bump score of a research with this mult if it can use XP
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 3.5 		-- To which extent AI should care about ahead of time penalties to research


-- Design

NDefines.NAI.DIVISION_DESIGN_WEIGHTS = {							                -- Base values used by AI to evaluate value of a stat
	-- Army Values
	0.1, -- default_morale
	0.1, -- defense
	0.1, -- breakthrough
	0.1, -- hardness
	0.1, -- soft_attack
	0.1, -- hard_attack
	0.0, -- recon
	0.0, -- entrenchment
	0.0, -- initiative
	0.0, -- casualty_trickleback
	0.0, -- supply_consumption_factor
	0.0, -- supply_consumption
	0.0, -- suppression
	0.0, -- suppression_factor
	0.0, -- experience_loss_factor
	0.0, -- equipment_capture_factor
	0.0, -- fuel_capacity
	-- Navy Values
	0.0, -- surface_detection
	0.0, -- sub_detection
	0.0, -- surface_visibility
	0.0, -- sub_visibility
	0.0, -- lg attack
	0.0, -- lg piercing
	0.0, -- hg attack
	0.0, -- hg piercing
	0.0, -- torpedo
	0.0, -- sub attack
	0.0, -- anti air attack
	0.0, -- amphibious_defense
	0.0, -- naval_speed
	0.0, -- range
	0.0, -- mine plant
	0.0, -- mine sweep
	0.0, -- raiding coordination
	0.0, -- patrol coordination
	0.0, -- search and destroy coordination
	-- Air Values
	0.0, -- air_range
	0.1, -- air_defence
	0.1, -- air_attack
	0.1, -- air_agility
	0.1, -- air_bombing
	0.0, -- air_superiority
	0.1, -- naval_strike_attack
	0.0, -- naval_strike_targetting
	0.1, -- air_ground_attack
	0.0, -- air_visibility_factor
	-- Common Values
	0.1, -- max_organisation
	0.1, -- max_strength
	0.1, -- maximum_speed
	0.1, -- armor_value
	0.1, -- ap_attack
	0.1, -- reliability
	0.1, -- reliability_factor
	0.1, -- weight
	0.0, -- fuel_consumption
	0.0, -- fuel_consumption_factor
	-- Special Values
	0.1, -- strategic_attack
	0.1, -- carrier_size
	0.0, -- acclimatization hot gain
	0.0, -- acclimatization cold gain
	0.1, -- build_cost_ic
}

NDefines.NAI.DIVISION_UPGRADE_MIN_XP = 200				-- Minimum XP before attempting to upgrade a division template.
NDefines.NAI.DIVISION_CREATE_MIN_XP = 200				-- Minimum XP before attempting to create a fresh new division template.
NDefines.NAI.VARIANT_UPGRADE_MIN_XP = 200				-- Minimum XP before attempting to create a new variant.
NDefines.NAI.UPGRADE_XP_RUSH_UPDATE = 5				-- If XP is above this on the daily tick the AI will attempt to spend it

NDefines.NAI.DIVISION_DESIGN_MANPOWER_WEIGHT = 0 --0.005
NDefines.NAI.DIVISION_DESIGN_STOCKPILE_WEIGHT = 0 --0.01

NDefines.NAI.DIVISION_DESIGN_COMBAT_WIDTH_TARGET_WEIGHT = -10000 -- -200	        -- This score is reduced the farther the width is from the target width (if set)

NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 7 --7
NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.25 --0.1
NDefines.NAI.UPGRADES_DEFICIT_LIMIT_DAYS = 365 --180 --50                           -- Ai will avoid upgrading units in the field to new templates if it takes longer than this to fullfill their equipment need

-- Division production 

NDefines.NAI.WANTED_UNITS_INDUSTRY_FACTORY = 0 --1 		        			-- How many units a country wants is partially based on how much military industry that is available

NDefines.NAI.DEPLOYED_UNIT_MANPOWER_RATIO_TO_BUFFER_WARTIME = 0.2 				-- deployment will try to buffer a ratio of deployed manpower (for reinforcements) during war time
NDefines.NAI.DEPLOYED_UNIT_MANPOWER_RATIO_TO_BUFFER_PEACETIME = 0.1     		-- deployment will try to buffer a ratio of deployed manpower (for reinforcements) during peace time

NDefines.NAI.MAX_AVAILABLE_MANPOWER_RATIO_TO_BUFFER_WARTIME = 0.2			-- deployment will try to buffer a ratio of manpower (for reinforcements) during war time
NDefines.NAI.MAX_AVAILABLE_MANPOWER_RATIO_TO_BUFFER_PEACETIME = 0.1		-- deployment will try to buffer a ratio of manpower (for reinforcements) during peace time

NDefines.NAI.MANPOWER_RATIO_REQUIRED_TO_PRIO_MOBILIZATION_LAW = 0.4		-- percentage of manpower in field is desired to be buffered for AI when it has upcoming wars or already at war. if it has less manpower, it will prio manpower laws



NDefines.NAI.MANPOWER_FREE_USAGE_THRESHOLD = 1 --500000					            -- If AI has this much manpower he doesn't care about the percentage
NDefines.NAI.MANPOWER_RESERVED_THRESHOLD = 0 --0.25					                -- The AI will not deploy more units if he goes below this percentag




NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 0.9 --0.95		                        -- Required percentage of training (1.0 = 100%) for AI to deploy unit in peacetime
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 0.25 --0.9 --0.25		                        -- Required percentage of training (1.0 = 100%) for AI to deploy unit in wartime

NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 0.9 --0.95	                        -- Required percentage of equipment (1.0 = 100%) for AI to deploy unit in peacetime
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.85 --0.9		                        -- Required percentage of equipment (1.0 = 100%) for AI to deploy unit in wartime

NDefines.NAI.START_TRAINING_EQUIPMENT_LEVEL = 0.8 --0.9                               -- ai will not start to train if equipment drops below this level
NDefines.NAI.STOP_TRAINING_EQUIPMENT_LEVEL = 0.7 --0.8                                -- ai will not train if equipment drops below this level

-- Equipment production 

NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR = 0.5 -- 0.25	-- Base value for how much of currently used equipment the AI will at least strive to have in stock

NDefines.NAI.SHIPS_PRODUCTION_BASE_COST = 1
NDefines.NAI.NEEDED_NAVAL_FACTORIES_EXPENSIVE_SHIP_BONUS = 1000
NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0.01

NDefines.NAI.NAVAL_DOCKYARDS_SHIP_FACTOR = 1000			-- The extent to which number of dockyards play into amount of sips a nation wants
NDefines.NAI.NAVAL_BASES_SHIP_FACTOR = 1000				-- The extent to which number of naval bases play into amount of sips a nation wants
NDefines.NAI.NAVAL_STATES_SHIP_FACTOR = 1000			-- The extent to which number of states play into amount of sips a nation wants

NDefines.NAI.PRODUCTION_LINE_SWITCH_SURPLUS_NEEDED_MODIFIER = 0 -- 0.2 --delays the AI from upgrading air lines too long, this is handled by strategies instead

-- Fuel 

NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_ARMY_MAX_CONSUMPTION = 365  -- AI will try to buffer at least this amount of days on max consumption, will trade if necesarry and will go into fuel saving mode/aggresive mode using this buffer 
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_AIR_MAX_CONSUMPTION  = 365  -- AI will try to buffer at least this amount of days on max consumption, will trade if necesarry and will go into fuel saving mode/aggresive mode using this buffer
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_NAVY_MAX_CONSUMPTION = 365  -- AI will try to buffer at least this amount of days on max consumption, will trade if necesarry and will go into fuel saving mode/aggresive mode using this buffer

NDefines.NAI.FUEL_RATIO_ENTER_FUEL_SAVING_MODE = 0.15 						-- countries will enter fuel saving mode if they have less fuel ratio than this
	
NDefines.NAI.DAYS_FUEL_REMAINING_TO_EXIT_FUEL_SAVING_MODE = 45				-- countries will exit fuel saving mode if they will fill their tanks in this number of days and their fuel ratio is above next define
NDefines.NAI.DAYS_FUEL_REMAINING_TO_EXIT_FUEL_SAVING_MODE_FUEL_RATIO = 0.6
	
	
NDefines.NAI.FUEL_RATIO_ENTER_AGRESSIVE_FUEL_MODE = 0.8 					-- countries will enter aggressive fuel usage mode if they have more fuel ratio than this
NDefines.NAI.DAYS_TO_FILL_BUFFER_TO_ENTER_AGRESSIVE_FUEL_MODE = 45			-- countries will enter aggressive fuel usage mode if they will fill their buffers in this number of days and their fuel ratio is above next define
NDefines.NAI.DAYS_TO_FILL_BUFFER_TO_ENTER_AGRESSIVE_FUEL_MODE_FUEL_RATIO = 0.6
	
NDefines.NAI.FUEL_EXIT_ENTER_AGRESSIVE_FUEL_MODE = 0.5 						-- countries will exit aggressive fuel usage mode if they have less fuel ratio than this
NDefines.NAI.DAYS_TO_FILL_BUFFER_TO_EXIT_AGRESSIVE_FUEL_MODE = 60			-- countries will exit aggressive fuel usage mode if they will be out of fuel in this number of days and their fuel ratio is below next define
NDefines.NAI.DAYS_TO_FILL_BUFFER_TO_EXIT_AGRESSIVE_FUEL_MODE_FUEL_RATIO = 0.5

-- Diplomacy

NDefines.NAI.DIPLOMACY_SEND_MAX_FACTION = 0.75
NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.6
NDefines.NAI.MIN_ANTAGONIZE_FOR_WARGOAL_JUSTIFICATION = -100	-- AI countries will not fabricate claims against countries with an antagonization value lower than this.

NDefines.NAI.REQUEST_LEND_LEASE_STOCKPILE_RATIO_LAND = 0.1		-- Ratio to send stockpile from equipment
NDefines.NAI.REQUEST_LEND_LEASE_PRODUCTION_DAYS_LAND = 28		-- Count of daily production amount of equipment to send
NDefines.NAI.REQUEST_LEND_LEASE_STOCKPILE_RATIO_AIR = 0.03		-- Ratio to send stockpile from equipment
NDefines.NAI.REQUEST_LEND_LEASE_PRODUCTION_DAYS_AIR = 10		-- Count of daily production amount of equipment to send
NDefines.NAI.REQUEST_LEND_LEASE_STOCKPILE_RATIO_NAVAL = 0.1		-- Ratio to send stockpile from equipment
NDefines.NAI.REQUEST_LEND_LEASE_PRODUCTION_DAYS_NAVAL = 28		-- Count of daily production amount of equipment to send


-- Economy

NDefines.NAI.TRADEABLE_FACTORIES_FRACTION = 1

NDefines.NAI.WAIT_YEARS_BEFORE_FREER_BUILDING = 0

NDefines.NAI.DOCKYARDS_PER_NAVAL_DESIRE_EFFECT = -100.0

NDefines.NAI.FUEL_RATIO_TO_EXIST_FUEL_SAVING_MODE = 0.40

-- Political Power 

NDefines.NAI.NEW_LEADER_EXTRA_PP_FACTOR = 1 --2.0								 -- Country must have at least this many times extra PP to get new admirals or army leaders

NDefines.NAI.DIPLOMACY_IMPROVE_RELATION_COST_FACTOR = 21.0                       -- Desire to boost relations subtracts the cost multiplied by this

-- Land AI 

NDefines.NMilitary.PLAN_EXECUTE_RUSH = -10									-- When looking for an attach target, this score limit is required in the battle plan to consider province for attack
NDefines.NAI.FALLBACK_LOSING_FACTOR = 0.0 					                    -- The lower this number  the longer the AI will hold the line before sending them to the fallback line


NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.65							-- Minimum org % for a unit to actively attack an enemy unit when executing a plan
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.75						-- Minimum strength for a unit to actively attack an enemy unit when executing a plan

NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.65							-- (LOW,MED,HIGH) corresponds to the plan execution agressiveness level.
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.65	

NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.55		
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.55	

NDefines.NAI.PLAN_FACTION_STRONG_TO_EXECUTE = 0.80 --0.80	0.60		        -- % or more of units in an order to consider ececuting the plan
NDefines.NAI.ORG_UNIT_STRONG = 0.85												-- Organization % for unit to be considered strong
NDefines.NAI.STR_UNIT_STRONG = 0.95												-- Strength (equipment) % for unit to be considered strong

NDefines.NAI.PLAN_FACTION_NORMAL_TO_EXECUTE = 0.65
NDefines.NAI.ORG_UNIT_NORMAL = 0.75 --6												-- Organization % for unit to be considered normal
NDefines.NAI.STR_UNIT_NORMAL = 0.85 --6												-- Strength (equipment) % for unit to be considered normal

NDefines.NAI.PLAN_FACTION_WEAK_TO_ABORT = 0.65 --0.50		0.65		        -- % or more of units in an order to consider ececuting the plan
NDefines.NAI.ORG_UNIT_WEAK = 0.5 --0.45												-- Organization % for unit to be considered weak
NDefines.NAI.STR_UNIT_WEAK = 0.6 --0.45												-- Strength (equipment) % for unit to be considered weak


NDefines.NAI.AI_FRONT_MOVEMENT_FACTOR_FOR_READY = 0.5			                -- If less than this fraction of units on a front is moving  AI sees it as ready for action

NDefines.NAI.PLAN_ACTIVATION_MAJOR_WEIGHT_FACTOR = 1		                    -- AI countries will hold on activating plans if stronger countries have plans in the same location. Majors count extra (value of 1 will negate this)
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 1 		                -- AI countries will hold on activating plans if player controlled countries have plans in the same location. Majors count extra (value of 1 will negate this)

NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 5000					                -- A country with less provinces than this will not draw fallback plans  but rather station their troops along the front

NDefines.NAI.VP_GARRISON_VALUE_FACTOR = 1				-- Extent to which VP garrisons are prioritized, based on VP value and compared to other priority values.
NDefines.NAI.PLAN_MOVE_MIN_ORG_TO_ENEMY_PROVINCE = 20.0	-- Minimum organization a unit must have to consider moving into an enemy province (not attack move)
NDefines.NAI.STATE_GARRISON_MAX_UNITS = 4				-- Max units to guard a garrison under normal circumstances (isolated core areas like England has is excempt)
NDefines.NAI.FRONT_REASSIGN_DISTANCE = 120.0			-- If a unit is this far away from a front it is not considered to be assigned to it unless the new front is much more important
NDefines.NAI.OLD_FRONT_IMPORTANCE_FACTOR = 1.50			-- If a unit is considered for reassignment, the importance of both new and old front is considered with a weight applied to the old ones score
NDefines.NAI.MIN_STATE_VALUE_TO_PROTECT = 7.5			-- When AI is considering which states to protect it looks at state values to consider if it is worth it.

NDefines.NAI.DESIRED_UNITS_FACTOR_AREA_ORDER = 0.8				-- Factor for desired number of units to assign to area defense orders
NDefines.NAI.MIN_UNITS_FACTOR_AREA_ORDER = 0.6					-- Factor for min number of units to assign to area defense orders

NDefines.NAI.MAX_UNITS_FACTOR_FRONT_ORDER = 3.0					-- Factor for max number of units to assign to area front orders
NDefines.NAI.DESIRED_UNITS_FACTOR_FRONT_ORDER = 3.0				-- Factor for desired number of units to assign to area front orders
NDefines.NAI.MIN_UNITS_FACTOR_FRONT_ORDER = 2.0					-- Factor for min number of units to assign to area front orders

NDefines.NAI.MICRO_POCKET_SIZE = 5						-- Pockets with a size equal to or lower than this will be mocroed by the AI for efficiency.
NDefines.NAI.ENTRENCHMENT_WEIGHT = 2.5					-- AI should favour units with less entrenchment when assigning units around.
NDefines.NAI.FRONT_TERRAIN_DEFENSE_FACTOR = 7.0			-- Multiplier applied to unit defense modifier for terrain on front province multiplied by terrain importance
NDefines.NAI.FRONT_TERRAIN_ATTACK_FACTOR = 7.0			-- Multiplier applied to unit attack modifier for terrain on enemy front province multiplied by terrain importance
NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.3				            -- % or more average plan preparation before executing
NDefines.NAI.MAX_SUPPLY_DIVISOR = 3.5							-- To make sure the AI does not overdeploy divisions. Higher number means more supply per unit.
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 5					-- AI goes through its orders and checks if there are situations to take advantage of
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.42				-- AI will not launch attacks against heavily defended fronts unless they consider to have this level of advantage (1.0 = 100%)
NDefines.NAI.HOUR_BAD_COMBAT_REEVALUATE = 65                   -- if we are in combat for this amount and it goes shitty then try skipping it 
NDefines.NAI.MAX_DIST_PORT_RUSH = 25.0							-- If a unit is in enemy territory with no supply it will consider nearby ports within this distance.
NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.7			-- Cancel unit production if below this to get resources out to units in the field
NDefines.NAI.MIN_MANPOWER_TO_BUILD_UNITS = 0.7					-- Cancel unit production if below this to get resources out to units in the field
NDefines.NAI.AVERAGE_SUPPLY_USE_PESSIMISM = 1.5					-- Multiplier for when AI calculates average supply use of entire army.
NDefines.NAI.FRONT_CUTOFF_MIN_EDGE_PROXIMITY = 4				-- Minimum number of provinces to the front edge to determine for cutoff oportunity.


	

-- Naval AI 

NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_CONVOY_DEFENSE_MIN = 0.40 -- maximum ratio of all screen-ships forces to be used in convoy defense (increases up to max as AI loses convoys).

NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING = 0 -- maximum ratio of screens forces to be used in mine sweeping

NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_LAYING = 0 -- maximum ratio of screens forces to be used in mine laying


NDefines.NAI.MAX_DISTANCE_NALAV_INVASION = 300.0								-- AI is extremely unwilling to plan naval invasions above this naval distance limit.
NDefines.NAI.ENEMY_NAVY_STRENGTH_DONT_BOTHER = 1000								-- If the enemy has a navy at least these many times stronger that the own, don't bother invading


NDefines.NAI.MAX_INVASION_SIZE = 12

NDefines.NAI.INVASION_DISTANCE_RANDOMNESS = 300									-- This higher the value the more unpredictable the invasions. Compares to actual map distance in pixels.

NDefines.NAI.MISSING_CONVOYS_BOOST_FACTOR = 0.0
NDefines.NAI.CONVOY_NEED_SAFETY_BUFFER = 0

NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0.1		-- AI will not replace ships being built by newer types if progress is above this	

NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 3.5					-- screens to capital/carrier count in carrier & capital taskforces

NDefines.NAI.HIGH_PRIO_NAVAL_MISSION_SCORES = {  -- priorities for regions to get assigned to a mission
	0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
	3800, -- PATROL		
	1000, -- STRIKE FORCE 
	1500, -- CONVOY RAIDING
	1000, -- CONVOY ESCORT
	-1, -- MINES PLANTING	
	300, -- MINES SWEEPING	
	0, -- TRAIN
	0, -- RESERVE_FLEET
	1000, -- NAVAL INVASION SUPPORT
}

NDefines.NAI.MAX_MISSION_PER_TASKFORCE = {  -- max mission region/taskforce ratio
	0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
	1.5, -- PATROL		
	6, -- STRIKE FORCE 
	1.5, -- CONVOY RAIDING
	4, -- CONVOY ESCORT
	-1, -- MINES PLANTING
	1, -- MINES SWEEPING
	0, -- TRAIN
	0, -- RESERVE_FLEET
	10, -- NAVAL INVASION SUPPORT
}

-- Air AI 


NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = 1

NDefines.NAI.AIR_WING_REINFORCEMENT_LIMIT = 400

NDefines.NAI.NAVAL_AIR_SUPERIORITY_IMPORTANCE = 1.0                             -- [0.10] -- Strategic importance of air superiority ( amount of enemy planes in area )

NDefines.NAI.NAVAL_SHIP_IN_PORT_AIR_IMPORTANCE = 20.0                             -- [6.0]  -- Naval ship in the port air importance
NDefines.NAI.NAVAL_COMBAT_AIR_IMPORTANCE = 500.0                                     -- [12.0] -- Naval combat air importance

NDefines.NAI.NAVAL_IMPORTANCE_SCALE = 10.0                                        -- [1.0]  -- Naval total importance scale (every naval score get's multiplied by it)
NDefines.NAI.NAVAL_FIGHTERS_PER_PLANE = 1.0                                        -- [1.1]  -- Amounts of air superiority planes requested per enemy plane



NDefines.NAI.LAND_DEFENSE_CIVIL_FACTORY_IMPORTANCE = 100                           -- [50]   -- Strategic importance of civil factories
NDefines.NAI.LAND_DEFENSE_MILITARY_FACTORY_IMPORTANCE = 120                        -- [70]   -- Strategic importance of military factories
NDefines.NAI.LAND_DEFENSE_NAVAL_FACTORY_IMPORTANCE = 80                            -- [30]   -- Strategic importance of naval factories

NDefines.NAI.LAND_DEFENSE_FIGHERS_PER_PLANE = 0.1                                -- [1.0]  -- Amount of air superiority planes requested per enemy plane
NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_BOMBERS = 2                           -- [2.0]  -- Amount of air interceptor planes requested per enemy bomber
NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_PLANE = 0.0                             -- [1.0]  -- Amount of air interceptor planes requested per enemy plane (non bomber)

NDefines.NAI.LAND_COMBAT_FIGHTERS_PER_PLANE = 2                                    -- [1.1]  -- Amount of air superiority planes requested per enemy plane

NDefines.NAI.LAND_COMBAT_CAS_PER_ENEMY_ARMY = 0                                 -- [20]   -- Amount of CAS planes requested per enemy army

NDefines.NAI.STR_BOMB_MIN_ENEMY_FIGHTERS_IN_AREA = 400                            -- [300]  -- If amount of enemy fighters is higher than this mission won't perform
NDefines.NAI.STRATEGIC_BOMBING_DEFENCE_IMPORTANCE = 500.0
NDefines.NAI.ESCORT_BOMBERS_IMPORTANCE_MODIFIER = 3.0

NDefines.NAI.AIR_SUPERIORITY_MISSION_FACTOR = 1.0				-- AI air superiority mission factor
NDefines.NAI.CAS_MISSION_FACTOR = 1.4							-- AI cas mission factor
NDefines.NAI.INTERCEPTION_MISSION_FACTOR = 0.5					-- AI interception mission factor
NDefines.NAI.STREATEGIC_BOMBER_MISSION_FACTOR = 1.2				-- AI strategic bombing mission factor
NDefines.NAI.NAVAL_BOMBER_MISSION_FACTOR = 0.5					-- AI naval bombing mission factor
NDefines.NAI.NUKE_MISSION_FACTOR = 1.0						-- AI nuke mission factor
NDefines.NAI.PARADROP_MISSION_FACTOR = 1.0						-- AI paradrop mission factor
NDefines.NAI.KAMIKAZE_MISSION_FACTOR = 1.0						-- AI naval kamikaze mission factor
NDefines.NAI.PORT_STRIKE_MISSION_FACTOR = 1.0					-- AI port strike mission factor
NDefines.NAI.INDUSTRY_IC_AIR_IMPORTANCE_FACTOR = 0.02			-- AI very specific IC cost factor for air missions
NDefines.NAI.LAND_DEFENSE_FIGHERS_PER_PLANE = 1.1				-- Amount of air superiority planes requested per enemy plane
NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_BOMBERS = 2.0		-- Amount of air interceptor planes requested per enemy plane


NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 20						-- AI will generally attempt to merge fleets into this size but as a soft limit.
NDefines.NAI.INVASION_COASTAL_PROVS_PER_ORDER = 12								-- AI will consider one extra invasion per number of provinces stated here (num orders = total coast / this)








